sonar.projectName=${{ values.product }}-${{ values.component }}
sonar.projectKey=${{ values.product }}-${{ values.component }}
sonar.language=python
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
